parameters:
    botanick.serializer.service.class: Botanick\SerializerBundle\Serializer\Serializer
    botanick.serializer.data_serializer.scalar.class: Botanick\SerializerBundle\Serializer\DataSerializer\ScalarSerializer
    botanick.serializer.data_serializer.resource.class: Botanick\SerializerBundle\Serializer\DataSerializer\ResourceSerializer
    botanick.serializer.data_serializer.null.class: Botanick\SerializerBundle\Serializer\DataSerializer\NullSerializer
    botanick.serializer.data_serializer.array.class: Botanick\SerializerBundle\Serializer\DataSerializer\ArraySerializer
    botanick.serializer.data_serializer.traversable.class: Botanick\SerializerBundle\Serializer\DataSerializer\TraversableSerializer

services:
    botanick.serializer.service:
        class: %botanick.serializer.service.class%

    botanick.serializer:
        alias: botanick.serializer.service

    botanick.serializer.data_serializer.scalar:
        class: %botanick.serializer.data_serializer.scalar.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: -100 }

    botanick.serializer.data_serializer.resource:
        class: %botanick.serializer.data_serializer.resource.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: -100 }

    botanick.serializer.data_serializer.null:
        class: %botanick.serializer.data_serializer.null.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: -100 }

    botanick.serializer.data_serializer.array:
        class: %botanick.serializer.data_serializer.array.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: -100 }

    botanick.serializer.data_serializer.traversable:
        class: %botanick.serializer.data_serializer.traversable.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: -100 }
