parameters:
    botanick.serializer.service.class: Botanick\Serializer\Serializer\Serializer
    botanick.serializer.config_loader.array.class: Botanick\Serializer\Serializer\Config\SerializerArrayConfigLoader
    botanick.serializer.config_loader.files.class: Botanick\Serializer\Serializer\Config\SerializerFilesConfigLoader
    botanick.serializer.config_loader.dirs.class: Botanick\Serializer\Serializer\Config\SerializerDirsConfigLoader
    botanick.serializer.config_loader.bundles.class: Botanick\SerializerBundle\Serializer\Config\SerializerBundlesConfigLoader
    botanick.serializer.config_loader.cache.class: Botanick\Serializer\Serializer\Config\SerializerConfigCache
    botanick.serializer.config_loader.cache_dumper.class: Botanick\Serializer\Serializer\Config\SerializerConfigCacheDumper
    botanick.serializer.data_serializer.scalar.class: Botanick\Serializer\Serializer\DataSerializer\ScalarSerializer
    botanick.serializer.data_serializer.resource.class: Botanick\Serializer\Serializer\DataSerializer\ResourceSerializer
    botanick.serializer.data_serializer.null.class: Botanick\Serializer\Serializer\DataSerializer\NullSerializer
    botanick.serializer.data_serializer.array.class: Botanick\Serializer\Serializer\DataSerializer\ArraySerializer
    botanick.serializer.data_serializer.traversable.class: Botanick\Serializer\Serializer\DataSerializer\TraversableSerializer
    botanick.serializer.data_serializer.datetime.class: Botanick\Serializer\Serializer\DataSerializer\DateTimeSerializer
    botanick.serializer.data_serializer.object.class: Botanick\Serializer\Serializer\DataSerializer\ObjectSerializer

services:
    botanick.serializer.service:
        class: %botanick.serializer.service.class%

    botanick.serializer:
        alias: botanick.serializer.service

    botanick.serializer.config_loader.array:
        class: %botanick.serializer.config_loader.array.class%
        public: false
        arguments:
            - %botanick_serializer.config.config_loader.array%

    botanick.serializer.config_loader.files:
        class: %botanick.serializer.config_loader.files.class%
        public: false
        arguments:
            - %botanick_serializer.config.config_loader.files%
            - @botanick.serializer.config_loader.cache

    botanick.serializer.config_loader.dirs:
        class: %botanick.serializer.config_loader.dirs.class%
        public: false
        arguments:
            - %botanick_serializer.config.config_loader.dirs%
            - @botanick.serializer.config_loader.cache

    botanick.serializer.config_loader.bundles:
        class: %botanick.serializer.config_loader.bundles.class%
        public: false
        arguments:
            - @file_locator
            - %botanick_serializer.config.config_loader.bundles%
            - @botanick.serializer.config_loader.cache

    botanick.serializer.config_loader:
        alias: botanick.serializer.config_loader.bundles
        public: false

    botanick.serializer.config_loader.cache:
        class: %botanick.serializer.config_loader.cache.class%
        public: false
        arguments:
            - %botanick_serializer.config_loader.cache.cache_class_prefix%
            - %kernel.debug%
            - %kernel.cache_dir%
            - @botanick.serializer.config_loader.cache_dumper

    botanick.serializer.config_loader.cache_dumper:
        class: %botanick.serializer.config_loader.cache_dumper.class%
        public: false

    botanick.serializer.data_serializer.scalar:
        class: %botanick.serializer.data_serializer.scalar.class%
        public: false
        calls:
            - [ 'setDefaultOptions', [ %botanick_serializer.config.data_serializer.scalar.options% ] ]
        tags:
            - { name: botanick.serializer.data_serializer, priority: %botanick_serializer.config.data_serializer.scalar.priority% }

    botanick.serializer.data_serializer.resource:
        class: %botanick.serializer.data_serializer.resource.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: %botanick_serializer.config.data_serializer.resource.priority% }

    botanick.serializer.data_serializer.null:
        class: %botanick.serializer.data_serializer.null.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: %botanick_serializer.config.data_serializer.null.priority% }

    botanick.serializer.data_serializer.array:
        class: %botanick.serializer.data_serializer.array.class%
        public: false
        tags:
            - { name: botanick.serializer.data_serializer, priority: %botanick_serializer.config.data_serializer.array.priority% }

    botanick.serializer.data_serializer.traversable:
        class: %botanick.serializer.data_serializer.traversable.class%
        public: false
        calls:
            - [ 'setObjectSerializer', [ @botanick.serializer.data_serializer.object ] ]
        tags:
            - { name: botanick.serializer.data_serializer, priority: %botanick_serializer.config.data_serializer.traversable.priority% }

    botanick.serializer.data_serializer.datetime:
        class: %botanick.serializer.data_serializer.datetime.class%
        public: false
        calls:
            - [ 'setDefaultOptions', [ %botanick_serializer.config.data_serializer.datetime.options% ] ]
        tags:
            - { name: botanick.serializer.data_serializer, priority: %botanick_serializer.config.data_serializer.datetime.priority% }

    botanick.serializer.data_serializer.object:
        class: %botanick.serializer.data_serializer.object.class%
        public: false
        calls:
            - [ 'setDefaultOptions', [ %botanick_serializer.config.data_serializer.object.options% ] ]
            - [ 'setConfigLoader', [ @botanick.serializer.config_loader ] ]
        tags:
            - { name: botanick.serializer.data_serializer, priority: %botanick_serializer.config.data_serializer.object.priority% }
